### ISSUE TITLE
thread 'main' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:255:9

### ISSUE THREAD

**Issue by hvram1** [libra/libra#225]
# 🐛 Bug

I ran the command 
<code>
cargo run -p libra_swarm -- -s
</code>
and got the error about 
thread 'main' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:255:9 

## To reproduce

I am running on Ubuntu 18.04 behind a corporate proxy . I ran the command
<code>
cargo build --all --bins
</code>
It gave an issue of missing zlib libraries and i had to install 
<code>
sudo apt-get install zlib1g-dev
</code>

```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
   Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/libra_swarm -s`
Faucet account created in file "/tmp/keypair.LYCFh8HC7tOC/temp_faucet_keys"
Base directory containing logs and configs: "/tmp/.tmpN0aKAY"
Base directory containing logs and configs: "/tmp/.tmpDAPOvJ"
Base directory containing logs and configs: "/tmp/.tmphgjnz0"
Base directory containing logs and configs: "/tmp/.tmp6myTVs"
Base directory containing logs and configs: "/tmp/.tmpMnnmdc"
thread 'main' panicked at 'Max out 5 attempts to launch swarm', libra_swarm/src/swarm.rs:255:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Libra Version -->
- rustup 1.18.3 (435397f48 2019-05-22)
- Ubuntu 18.04 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


## Additional context

I checked the /tmp directory . I see other .tmp files containing the metrics folder being created . But I do not see the keypair directory or the logs and config directory ( the permissions exist ) . I assumed the directories were cleaned up on exit but even while the server was running I do not see any of these directories getting created

**Comment by xfyfb** [comment]
Thanks for the report. The keypair and logs are probably deleted after the run failed libra swarm run. Does it always fail? One or some of the 5 validators might not start successfully. Could you check the log and see why the validators failed to start?

**Comment by hvram1** [comment]
Could you tell me where the logs are present ?

On Wednesday, June 26, 2019, xfyfb <notifications@github.com> wrote:
> Thanks for the report. The keypair and logs are probably deleted after
the run failed libra swarm run. Does it always fail? One or some of the 5
validators might not start successfully. Could you check the log and see
why the validators failed to start?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/Uv9XSC2TVxye-nyimQHqlgrpUM-DM7cWmuKbBHtaP9Wn4wEH-Tm5t9I5bQdaV4PIljTHl5Hrn4CFir91RYHRqUuoJQ561Z-RVXDzD6b70iASU9-CRMrY_GiB2p5AIoA7fev300tWkPqUOc0198r9d7lDNOBS8rVwHR6nNintVIZCqZ8VYG2RRuQo5PmDOAPzwU581hqod1ucvH_FFNu1SiJlDITFqLoCEx66C5BAyQ=s0-d-e1-ft#https://github.com/notifications/beacon/AADNEDHVTEPFKDBFRRWTY4DP4OT2FA5CNFSM4H3QH3Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYUJZZI.gif>

**Comment by hvram1** [comment]
And yes it always fails

On Wednesday, June 26, 2019, xfyfb <notifications@github.com> wrote:
> Thanks for the report. The keypair and logs are probably deleted after
the run failed libra swarm run. Does it always fail? One or some of the 5
validators might not start successfully. Could you check the log and see
why the validators failed to start?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/Uv9XSC2TVxye-nyimQHqlgrpUM-DM7cWmuKbBHtaP9Wn4wEH-Tm5t9I5bQdaV4PIljTHl5Hrn4CFir91RYHRqUuoJQ561Z-RVXDzD6b70iASU9-CRMrY_GiB2p5AIoA7fev300tWkPqUOc0198r9d7lDNOBS8rVwHR6nNintVIZCqZ8VYG2RRuQo5PmDOAPzwU581hqod1ucvH_FFNu1SiJlDITFqLoCEx66C5BAyQ=s0-d-e1-ft#https://github.com/notifications/beacon/AADNEDHVTEPFKDBFRRWTY4DP4OT2FA5CNFSM4H3QH3Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYUJZZI.gif>

**Comment by xfyfb** [comment]
Oh, I forgot the log might be deleted in your case. It should be under base_dir/logs. 
Can you try to use -n parameter of libra swarm to start with fewer nodes, e.g
 cargo run -p libra_swarm -- -n 1
to run with 1 node.

**Comment by hvram1** [comment]
I ran this in a different machine but the same configuration ( Ubuntu 18.04 ) . 

The only difference was that this was **not behind a corporate proxy** 

And it works without any issues . 

There could be a possibility that the files were committed during this time . The current version of my git clone is 

<code>
git rev-parse HEAD
737839b744794c0ca3be3db2934de7ebf056639a
</code> 

I do not have access to the other environment currently . I will do a check and update the git rev-parse version of the other installation . 

BTW the logs directory does not seem to exist in the **base_dir/logs**

**Comment by hvram1** [comment]
This seems to be an issue with the proxy settings . I had to set the http_proxy and the https_proxy variables for the cargo command to work . But using this causes the libra_swarm to fail to connect to the localhost . I solved the problem by
<code>
unset http_proxy; unset https_proxy ; cargo run -p libra_swarm -- -s
</code>
and things work .

**Comment by xfyfb** [comment]
Glad that it is resolved. Could you close it if there is no other isssue?

**Comment by utensil** [comment]
I have encountered the same issue but not behind a corporate proxy and without `http*_proxy` enviroment variables set, so the solution above would not work in my case.

The panic message (same as this issue) has no indication of what went wrong, the stack trace is not helpful too(all from `core::` or `std::`). Still investigating.

**Comment by utensil** [comment]
It turns out the logs are in temp location and deleted when panicked. Take a look at the code, just change the parameter `tee_logs` of `LibraSwarm::launch_swarm` from `false` to `true`, the log will be printed to stderr.

The relevant part of the log looks like this:

```
[8deeeaed] I0629 15:36:17.832982 123145309089792 execution/executor/src/lib.rs:85] Startup info is empty. Will start from GENESIS.
[8deeeaed] D0629 15:36:17.833728 123145309089792 execution/executor/src/lib.rs:172] Received request to execute block. Parent id: 5052455f47454e455349535f424c4f434b5f4944000000000000000000000000. Id: 47454e455349535f424c4f434b5f494400000000000000000000000000000000.
[8deeeaed] D0629 15:36:17.837146 123145309089792 execution/executor/src/block_processor.rs:627] Execution status: [Keep(Execution(Executed))]
[8deeeaed] D0629 15:36:17.841612 123145309089792 execution/executor/src/lib.rs:204] Received request to commit block 47454e455349535f424c4f434b5f494400000000000000000000000000000000.
[8deeeaed] D0629 15:36:17.842989 123145309089792 storage/storage_service/src/lib.rs:259] [GRPC] Storage::save_transactions
[8deeeaed] I0629 15:36:17.848332 123145309089792 execution/executor/src/lib.rs:162] GENESIS transaction is committed.
[8deeeaed] D0629 15:36:17.863191 123145309089792 libra_node/src/main_node.rs:226] Execution service started in 33 ms
[8deeeaed] D0629 15:36:17.866759 123145309089792 network/src/peer_manager/mod.rs:528] listening on "/ip4/0.0.0.0/tcp/50462"
[8deeeaed] D0629 15:36:17.867859 123145309089792 network/src/peer_manager/mod.rs:545] Incoming connections listener Task started
[8deeeaed] D0629 15:36:17.868415 123145309089792 libra_node/src/main_node.rs:237] Network started in 5 ms
[8deeeaed] D0629 15:36:17.877199 123145309089792 libra_node/src/main_node.rs:242] AC started in 8 ms
[8deeeaed] E0629 15:36:17.877394000 123145484783616 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
```

while other applications work well on my MBP without complaining `Too many open files`.

**Comment by Destanek** [comment]
I've faced the same problem and this one doesn't work for me.
> ` unset http_proxy; unset https_proxy ; cargo run -p libra_swarm -- -s `

Then I printed out the log some attempt got this:

```
[8deeeaed] D0630 09:42:40.041255 123145534431232 libra_node/src/main_node.rs:219] Storage service started in 247 ms
[8deeeaed] D0630 09:42:40.043770 123145534431232 storage/storage_service/src/lib.rs:271] [GRPC] Storage::get_executor_startup_info
[8deeeaed] E0630 09:42:40.044950 123145534431232 common/grpc_helpers/src/lib.rs:20] Failed to reply error due to RemoteStopped
[8deeeaed] C0630 09:42:42.446081 123145534431232 common/crash_handler/src/lib.rs:68] reason = 'Failed to read startup info from storage.: ErrorMessage { msg: "grpc error: RpcFailure(RpcStatus { status: Unknown, details: Some(\"Stream removed\") })" }'
```

and some got this:
```
[8deeeaed] D0630 09:42:43.073476 123145494695936 libra_node/src/main_node.rs:219] Storage service started in 234 ms
[8deeeaed] D0630 09:42:43.075404 123145494695936 storage/storage_service/src/lib.rs:271] [GRPC] Storage::get_executor_startup_info
[8deeeaed] C0630 09:42:45.472870 123145494695936 common/crash_handler/src/lib.rs:68] reason = 'Failed to read startup info from storage.: ErrorMessage { msg: "grpc error: RpcFailure(RpcStatus { status: Unknown, details: Some(\"Stream removed\") })" }'
```

I also try and still cannot run it locally even I'm not behind a corporate proxy.
> ulimit -n 8192

**Comment by lkrit** [comment]
> It turns out that the logs are in temp location and deleted when panicked. Take a look at the code, just change the parameter `tee_logs` of `LibraSwarm::launch_swarm` from `false` to `true`, the log will be printed to stderr.
> 
> The relevant part of the log looks like this:
> 
> ```
> [8deeeaed] I0629 15:36:17.832982 123145309089792 execution/executor/src/lib.rs:85] Startup info is empty. Will start from GENESIS.
> [8deeeaed] D0629 15:36:17.833728 123145309089792 execution/executor/src/lib.rs:172] Received request to execute block. Parent id: 5052455f47454e455349535f424c4f434b5f4944000000000000000000000000. Id: 47454e455349535f424c4f434b5f494400000000000000000000000000000000.
> [8deeeaed] D0629 15:36:17.837146 123145309089792 execution/executor/src/block_processor.rs:627] Execution status: [Keep(Execution(Executed))]
> [8deeeaed] D0629 15:36:17.841612 123145309089792 execution/executor/src/lib.rs:204] Received request to commit block 47454e455349535f424c4f434b5f494400000000000000000000000000000000.
> [8deeeaed] D0629 15:36:17.842989 123145309089792 storage/storage_service/src/lib.rs:259] [GRPC] Storage::save_transactions
> [8deeeaed] I0629 15:36:17.848332 123145309089792 execution/executor/src/lib.rs:162] GENESIS transaction is committed.
> [8deeeaed] D0629 15:36:17.863191 123145309089792 libra_node/src/main_node.rs:226] Execution service started in 33 ms
> [8deeeaed] D0629 15:36:17.866759 123145309089792 network/src/peer_manager/mod.rs:528] listening on "/ip4/0.0.0.0/tcp/50462"
> [8deeeaed] D0629 15:36:17.867859 123145309089792 network/src/peer_manager/mod.rs:545] Incoming connections listener Task started
> [8deeeaed] D0629 15:36:17.868415 123145309089792 libra_node/src/main_node.rs:237] Network started in 5 ms
> [8deeeaed] D0629 15:36:17.877199 123145309089792 libra_node/src/main_node.rs:242] AC started in 8 ms
> [8deeeaed] E0629 15:36:17.877394000 123145484783616 wakeup_fd_pipe.cc:40]         pipe creation failed (24): Too many open files
> ```
> 
> while other applications work well on my MBP without complaining `Too many open files`.
> 
> ```
> $ sysctl kern.maxfiles
> kern.maxfiles: 49152
> $ sysctl kern.maxfilesperproc
> kern.maxfilesperproc: 24576
> ```
> 
> They seem fine.
> 
> ```
> $ ulimit -a
> core file size          (blocks, -c) 0
> data seg size           (kbytes, -d) unlimited
> file size               (blocks, -f) unlimited
> max locked memory       (kbytes, -l) unlimited
> max memory size         (kbytes, -m) unlimited
> open files                      (-n) 8192
> pipe size            (512 bytes, -p) 1
> stack size              (kbytes, -s) 8192
> cpu time               (seconds, -t) unlimited
> max user processes              (-u) 1418
> virtual memory          (kbytes, -v) unlimited
> ```
> 
> Here it is. Just set `ulimit -n 8192` and it's up and running! 👏
> 
> TODO:
> 
> * [ ]  The reason for panicking should be reflected in the panic message.
> * [ ]  The parameter `tee_logs` should be exposed to CLI.
> * [ ]  The need for opening many files should be documented and there should be a recommended value for it.
> * [ ]  Proxy issue should be either documented or addressed.
> * [ ]  The logs are overwhelming even when no command is issued, takes up space really fast, ~17M/min.
> 
> Might create PRs for them later, but I've noticed that libra hasn't merged a single PR yet.
> 
> P.S. Just noticed that my report is almost a duplicate of #81 .

It's working for me now after running "ulimit -n 8192".  Thank you very much! (MacOS Mojave)

**Comment by bmwill** [comment]
I believe this should have been fixed. If you're still seeing the issue please reopen the issue.
